site_name: RT Corporation Software Tutorials
theme: 
  name: material
  custom_dir: overrides
  logo: img/rt-logo-32x32.png
  favicon: https://rt-net.github.io/tutorials/img/rt-logo-32x32.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - content.tabs.link

repo_url: https://github.com/rt-net/tutorials
edit_uri: edit/main/docs/

site_url: https://rt-net.github.io/tutorials/
copyright: Copyright &copy; 2021-2022 RT Corporation
use_directory_urls: false # ディレクトリ名/index.htmlを開く
site_description: 株式会社アールティのオンラインソフトウェアチュートリアルです。製品をより便利に使うためのソフトウェアの使い方を紹介しています。

### 拡張設定 ###

extra:
  social:
     - icon: fontawesome/brands/twitter
       link: https://twitter.com/rt_corp
       name: 株式会社アールティTwitterアカウント
     - icon: fontawesome/brands/github
       link: https://github.com/rt-net
       name: 株式会社アールティGitHubページ
  analytics:
    provider: google
    property: UA-69742588-2

extra_css:
  - css/colors.css
  - css/style.css

plugins:
  - search:
      lang:
        - en
        - ja
  - redirects:  # リダイレクト用
      redirect_maps:
        cranev2/index.md: cranev2/products.md
        crane-x7/index.md: crane-x7/products.md
        sciurus17/index.md: sciurus17/products.md
        raspimouse/index.md: raspimouse/products.md
        jnmouse/index.md: jnmouse/products.md
        raspicat/index.md: raspicat/products.md
        usb9imu/index.md: usb9imu/products.md

markdown_extensions:
  - attr_list  # 画像のalignを設定できる
  - pymdownx.tabbed:  # タブで文章を切り替えられる
      alternate_style: true
  - pymdownx.keys  # キーボード操作説明時のキーを装飾
  - admonition  # Warningとかの飾り付けができる
  - pymdownx.highlight  # コードブロック用
  - pymdownx.superfences  # コードブロック用
  - pymdownx.emoji:  # アイコンが使える
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - footnotes  # 注釈用
nav:
  - Home: 
    - トップページ: index.md
    - 免責事項・問い合わせについて: about.md
  - CRANE+ V2:
    - 1. 製品について: cranev2/products.md
    - 2. ROS 2:
      - 1. ROS 2のインストール: cranev2/ros/install.md
      - 2. ROS 2パッケージのインストール: cranev2/ros/package-install.md
      - 3. ROS 2サンプルの実行（実機）: cranev2/ros/samples.md
      - 4. ROS 2サンプルの実行（シミュレータ） : cranev2/ros/simulator.md
      - 5. カメラのキャリブレーション: cranev2/ros/camera-calibration.md
    - 3. 関連リンク集: cranev2/others.md
  - CRANE-X7:
    - 1. 製品について: crane-x7/products.md
    - 2. 関連リンク集: crane-x7/others.md
  - Sciurus17:
    - 1. 製品について: sciurus17/products.md
    - 2. 関連リンク集: sciurus17/others.md
  - Raspberry Pi Mouse:
    - 1. 製品について: raspimouse/products.md
    - 2. デバイスドライバ:
      - 1. インストール: raspimouse/driver/install.md
      - 2. サンプルを動かす: raspimouse/driver/samples.md
    - 3. ROS / ROS 2:
      - 1. ROS / ROS 2のインストール: raspimouse/ros/install.md
      - 2. ROS / ROS 2パッケージのインストール: raspimouse/ros/package-install.md
      - 3. ROS / ROS 2サンプルの実行: raspimouse/ros/samples.md
    - 4. シミュレータの実行:
      - 1. シミュレータのインストール: raspimouse/simulator/install.md
      - 2. ROS 2サンプルの実行（シミュレータ）: raspimouse/simulator/samples.md
    - 5. 関連リンク集: raspimouse/others.md
  - Jetson Nano Mouse:
    - 1. 製品について: jnmouse/products.md
    - 2. デバイスドライバ:
      - 1. Jetson Nano用OSの書き込みと初期設定: jnmouse/driver/install.md
      - 2. サンプルを動かす: jnmouse/driver/samples.md
    - 3. AI教材:
      - Jupyter Notebookの準備: jnmouse/jupyter-notebook/install.md
      - Jupyter Notebookの実行: jnmouse/jupyter-notebook/example.md
    - 4. ROS:
      - 1. ROSのインストール方法: jnmouse/ros/install.md
      - 2. ROSパッケージのインストール: jnmouse/ros/package-install.md
      - 3. ROSサンプルの実行: jnmouse/ros/samples.md
      - 4. シミュレータの実行: jnmouse/ros/simulator.md
    - 5. 関連リンク集: jnmouse/others.md
  - Raspberry Pi Cat:
    - 1. 製品について: raspicat/products.md
    - 2. デバイスドライバ:
      - 1. インストール: raspicat/driver/install.md
      - 2. サンプルを動かす: raspicat/driver/samples.md
    - 3. ROS / ROS 2:
      - 1. ROS / ROS 2のインストール: raspicat/ros/install.md
      - 2. ROS / ROS 2パッケージのインストール: raspicat/ros/package-install.md
      - 3. ROS / ROS 2サンプルの実行: raspicat/ros/samples.md
    - 4. シミュレータの実行:
      - 1. シミュレータのインストール: raspicat/simulator/install.md
      - 2. サンプルを動かす: raspicat/simulator/samples.md
    - 5. 関連リンク集: raspicat/others.md
  - USB出力9軸IMUセンサモジュール: 
    - 1. 製品について: usb9imu/products.md
    - 2. 関連リンク集: usb9imu/others.md

